CREATE OR ALTER TRIGGER TR_INSERTUSUARIO ON USUARIOS
INSTEAD OF INSERT
AS 
BEGIN 
	BEGIN TRY 
		BEGIN TRANSACTION 
			DECLARE @ID_USUARIO INT 
			DECLARE @NOMBRE_USUARIO VARCHAR(50)
			DECLARE @PASS VARCHAR(50)
			DECLARE @EMAIL VARCHAR(200)

			SELECT @NOMBRE_USUARIO = I.Usuario, @PASS = I.Pass, @EMAIL = I.EMAIL FROM inserted AS I 

			INSERT INTO USUARIOS (Usuario, Pass, TipoUser, EMAIL) VALUES (@NOMBRE_USUARIO, @PASS, 1, @EMAIL)
			
			SELECT @ID_USUARIO = @@IDENTITY 
			
			INSERT INTO DATOS_PERSONALES (ID_USUARIO) VALUES (@ID_USUARIO)

		COMMIT TRANSACTION
	END TRY 
	BEGIN CATCH
		RAISERROR('ERROR AL CREAR UN NUEVO USUARIO', 16, 1)
		ROLLBACK TRANSACTION
	END CATCH
END 